### ISSUE TITLE
Maintain comments from inside the decrypted yaml

### ISSUE THREAD

**Issue by marcqualie** [marcqualie/diffcrypt#25]
Currently, all commants are stripped and the keys are condensed. This doesn't affect the diffs, but it removes some context that may be present for explaining why certain keys exist, or what they're used for.

e.g.

```yaml
# Payments
stripe:
  publishable_key: pk_123
  secret_key: sk_123 # do not share this
```

```yaml
client: diffcrypt-0.3.3
cipher: aes-256-gcm
data:
  # Payments
  stripe:
    publishable_key: xxx-xxx-xxx
    secret_key: xxx-xxx-xxx # do not share this
```
